### PR TITLE
Enable Whoops Blocking only when Notices/Warnings come from specific Plugins/Themes

### PR DESCRIPTION
**Pull request by sumitpore**
By default the plugin blocks the execution whenever any kind of
notice/warning/error/exception occurs. This is really useful when
site is being built from the scratch, however, this could create a problem
when everything is not being built from the scratch — specifically when a notice
or warning comes from a plugin you did not develop.

This could be solved in one of the four ways.

### Skip Whoops Blocking for all Notices and Warnings
In `wps.php`, call `skipNoticesAndWarnings()` on `$wps` object. So it
might look like this
```diff
  $wps = new \Rarst\wps\Plugin();
+ $wps->skipNoticesAndWarnings(Except::blank());
  $wps->run();
```

`skipNoticesAndWarnings` accepts an object of `Rarst\wps\Except` class to
enable Whoops for notices/warnings of only specified plugins/themes.

### Enable Whoops' Notices/Warnings Blocking for Specific Plugins
```diff
  $wps = new \Rarst\wps\Plugin();
+ $wps->skipNoticesAndWarnings(Except::pluginsDirectories('akismet'));
  $wps->run();
```
Above example will skip all notices and warnings except coming from `akismet`
plugin. Pass multiple plugins to be excepted as separate arguments.

### Enable Whoops Notices/Warnings Blocking Blocking for Specific Themes
```diff
  $wps = new \Rarst\wps\Plugin();
+ $wps->skipNoticesAndWarnings(Except::themesDirectories('twentytwenty'));
  $wps->run();
```
Above example will skip all notices and warnings except coming from `twentytwenty`
theme. Pass multiple themes to be excepted as separate arguments.

### Enable Whoops Blocking for Specific Plugins and Themes together
```diff
  $wps = new \Rarst\wps\Plugin();
+ $exceptions = ['@plugins/akismet@', '@themes/twentytwenty@'];
+ $wps->skipNoticesAndWarnings(new Except($exceptions));
  $wps->run();
```

### CODE REVIEW

**Comment by Rarst** [comment]
I definitely get things being noisy when using this, thank you for suggesting handling it better! :)

My first thought while filtering sounds great, I am not confident that "plugin/theme" is a right criteria here. What about core?.. What about something in vendor?..

It might make sense for filter to be more generic and flexible, e.g. "(partial) path". And it might be useful to have both exclusion (not from these) and inclusions (only from these).

I will try to find some dedicated time to review PR and think some on direction next week.

**Comment by sumitpore** [comment]
It totally makes sense.

I have made a new commit which might help us achieve something closer to what you said.

So now by calling `silenceErrorsInPaths` on `$wps` object in `wps.php` file
before `$wps->run()`, one can define regex paths to silent errors.

While the first parameter of `silenceErrorsInPaths` accepts regex path,
the second parameter accepts error levels to silent. Multiple paths can
be passed through an array.

e.g. If you always want to silence errors coming from `vendor` directories,
writing something like below in `wps.php` will work
```diff
  $wps = new \Rarst\wps\Plugin();
+ $wps->silenceErrorsInPaths('@/vendor@', E_WARNING | E_NOTICE | E_USER_WARNING | E_USER_NOTICE);
  $wps->run();
```

Another Example -
If you want to allow notices/warnings from specific plugin but at the
same time silent errors that are coming from `vendor` directory which 
is inside the plugin, then you might write something like this in 
`wps.php`.
```diff
  $wps = new \Rarst\wps\Plugin();
+ $wps->skipNoticesAndWarnings(Except::pluginsDirectories('plugin-folder'));
+ $wps->silenceErrorsInPaths('@plugin-folder/vendor@', E_WARNING | E_NOTICE | E_USER_WARNING | E_USER_NOTICE);
  $wps->run();
```

**`silenceErrorsInPaths` will work only if error is being originated from files matching the regex.**

#### A little note about plugins/themes passed to `Rarst\wps\Except` to enable Whoops Blocking
WPS will enable Whoops Blocking even if a stack trace anywhere contains the plugins/themes passed to `Except` class. It is assumed that those plugins/themes were kind of somewhere responsible for it.

**Comment by sumitpore** [comment]
I have added support for regex patterns in `Except` class too. Multiple patterns can be passed in an array. Here is the example of regex pattern can be used. Using `preg_match` function patterns are matched. 

```diff
  $wps = new \Rarst\wps\Plugin();
+ $exceptions = ['@plugins/akismet@', '@themes/twentytwenty@'];
+ $wps->skipNoticesAndWarnings(new Except($exceptions));
  $wps->run();
```

**Comment by Rarst** [comment]
I went over changes and I am a little confused now, why reinvent this over using already available `Whoops\Run->silenceErrorsInPaths()` ?

I didn't know (or forgot :) it was available.

**Comment by sumitpore** [comment]
Umm.. `silenceErrorsInPaths` would allow to silence errors but probably if it is not sufficient to setup something like below example

Let's assume someone is creating a product & s/he wants to do following during development :
1. Hide all warnings/notices coming from Core WordPress.
2. Hide all warnings/notices coming from All active WordPress Plugins & themes _except the product being developed._
3. Hide all warnings/notices coming from `vendor` directory or third party libraries included inside the plugin.

Do you think this can be achieved with `silenceErrorsInPaths` alone?

**Comment by Rarst** [comment]
You can add multiple rules and it's regex so this seems doable to me.

Without writing out actual regex yet (I hadn’t had my tea :), the logic would be:

1. `/path/to/core`
2. `/path/to/plugins not followed by [name]`
3. `/path/to/plugins/[name]/vendor`

Makes sense?

**Comment by sumitpore** [comment]
Do you mean passing this kind of array to `silenceErrorsInPaths`?
```php
[
    '@html/wordpress@', // Core
    '@html/wordpress/wp-content/plugins/(?!my-plugin).*@', // Plugins folder except `my-plugin`
    '@html/wordpress/wp-content/plugins/my-plugin/vendor@', // Vendor
    '@html/wordpress/wp-content/themes@', // Themes
]
```

Needs to be tested but I guess because of `'@html/wordpress@'` this rule it will hide all warnings/notices of `my-plugin` too.

**Comment by Rarst** [comment]
Yep, exactly.

I am used to core being in dedicated folder, but in your case you could narrow down core rule to `wordpress not followed by wp-content`.

If this is good enough I think we don't need dedicated code, agreed? I would just document this in readme, it's not well covered upstream.

**Comment by sumitpore** [comment]
Yeah, that way it will work.

**Comment by Rarst** [comment]
Documented in readme, cheers. :) https://github.com/Rarst/wps#silence-for-path

**Pull request closed without merging**
